# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


currency_1 = "p"
minimum_input = 0
maximum_input = 10000


# from Page1 import Ui_Window1
# from Page2 import Ui_Window2
# from Page3 import Ui_Window3
# from Page5 import Ui_Window5

class Ui_MainWindow(object):

    def openWindow_021(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Window1()

        self.ui = Ui_Window1()
        self.ui.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def openWindow_022(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui2 = Ui_Window2()
        self.ui2 = Ui_Window2()
        self.ui2.setupUi(self.window2)
        MainWindow.hide()
        self.window2.show()

    def openWindow_023(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui3 = Ui_Window3()
        self.ui3.setupUi(self.window3)
        MainWindow.hide()
        self.window3.show()

    def openWindow_024(self):
        self.window4 = QtWidgets.QMainWindow()
        self.ui4 = Ui_Sub_MainWindow()
        self.ui4.setupUi(self.window4)
        MainWindow.hide()
        self.window4.show()

    def openWindow_025(self):
        self.window5 = QtWidgets.QMainWindow()
        self.ui5 = Ui_Window5()
        self.ui5.setupUi(self.window5)
        MainWindow.hide()
        self.window5.show()

    def quit(self):
        MainWindow.hide()
        self.Menu_Page.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedWidth(500)
        MainWindow.setFixedHeight(600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Menu_Page = QtWidgets.QFrame(self.centralwidget)
        self.Menu_Page.setGeometry(QtCore.QRect(0, 0, 531, 611))
        self.Menu_Page.setMinimumSize(QtCore.QSize(0, 0))
        self.Menu_Page.setAutoFillBackground(False)
        self.Menu_Page.setStyleSheet("background-color:rgb(62, 62, 62);")
        self.Menu_Page.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Menu_Page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Page.setObjectName("Menu_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Menu_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Menu_Header = QtWidgets.QLabel(self.Menu_Page)
        self.Main_Menu_Header.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Menu_Header.setFont(font)
        self.Main_Menu_Header.setStyleSheet("color:rgb(170, 255, 165);")
        self.Main_Menu_Header.setObjectName("Main_Menu_Header")
        self.verticalLayout.addWidget(self.Main_Menu_Header)
        self.btn_page_1 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_page_1.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_1.setAutoDefault(False)
        self.btn_page_1.setDefault(False)
        self.btn_page_1.setFlat(False)
        self.btn_page_1.setObjectName("btn_page_1")

############
        self.btn_page_1.clicked.connect(self.openWindow_021)

        self.verticalLayout.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_2.setObjectName("btn_page_2")

        self.btn_page_2.clicked.connect(self.openWindow_022)

        self.verticalLayout.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_3.setObjectName("btn_page_3")

        self.btn_page_3.clicked.connect(self.openWindow_023)

        self.verticalLayout.addWidget(self.btn_page_3)
        self.btn_page_4 = QtWidgets.QPushButton(self.Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_4.sizePolicy().hasHeightForWidth())
        self.btn_page_4.setSizePolicy(sizePolicy)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_4.setFont(font)
        self.btn_page_4.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_4.setObjectName("btn_page_4")

        self.btn_page_4.clicked.connect(self.openWindow_024)

        self.verticalLayout.addWidget(self.btn_page_4)
        self.btn_page_5 = QtWidgets.QPushButton(self.Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_5.sizePolicy().hasHeightForWidth())
        self.btn_page_5.setSizePolicy(sizePolicy)
        self.btn_page_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_5.setFont(font)
        self.btn_page_5.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_5.setObjectName("btn_page_5")

        ######
        self.btn_page_5.clicked.connect(self.openWindow_025)
        #####
        self.verticalLayout.addWidget(self.btn_page_5)
        self.btn_page_6 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_6.setFont(font)
        self.btn_page_6.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_6.setObjectName("btn_page_6")

        ####
        self.btn_page_6.clicked.connect(self.quit)
        #####
        self.verticalLayout.addWidget(self.btn_page_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Menu_Header.setText(_translate("MainWindow", "Coin Sorter - Main Menu"))
        self.btn_page_1.setText(_translate("MainWindow", "1 - Coin calculator"))
        self.btn_page_2.setText(_translate("MainWindow", "2 - Multiple coin calculator"))
        self.btn_page_3.setText(_translate("MainWindow", "3 - Print coin list"))
        self.btn_page_4.setText(_translate("MainWindow", "4 - Set details"))
        self.btn_page_5.setText(_translate("MainWindow", "5 - Display configurations details"))
        self.btn_page_6.setText(_translate("MainWindow", "6- Quit"))


############
# Page 1
############


##############
# Page_1 update design with functions
##############

class Ui_Window1(object):
    def openWindow120(self):
        self.window1_pg1 = QtWidgets.QMainWindow()
        self.ui1_pg1 = Ui_MainWindow()
        self.ui1_pg1.setupUi(self.window1_pg1)
        #Window1.hide()
        self.window1_pg1.show()

    def setupUi(self, Window1):
        Window1.setObjectName("Window1")
        Window1.resize(500, 600)
        Window1.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window1)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.label_1.setMinimumSize(QtCore.QSize(70, 150))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.Ammount_input = QtWidgets.QLineEdit(self.label_1)
        self.Ammount_input.setGeometry(QtCore.QRect(10, 210, 137, 24))
        self.Ammount_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ammount_input.setObjectName("Ammount_input")
        self.Display_Result_Label1 = QtWidgets.QLabel(self.label_1)
        self.Display_Result_Label1.setGeometry(QtCore.QRect(10, 300, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Display_Result_Label1.setFont(font)
        self.Display_Result_Label1.setStyleSheet("color:rgb(170, 255, 165);")
        self.Display_Result_Label1.setObjectName("Display_Result_Label1")
        self.label_Step1_2 = QtWidgets.QLabel(self.label_1)
        self.label_Step1_2.setGeometry(QtCore.QRect(12, 68, 264, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1_2.setFont(font)
        self.label_Step1_2.setStyleSheet("color: #FFF;")
        self.label_Step1_2.setObjectName("label_Step1_2")
        self.Remainder_Label = QtWidgets.QLabel(self.label_1)
        self.Remainder_Label.setGeometry(QtCore.QRect(10, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Remainder_Label.setFont(font)
        self.Remainder_Label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Remainder_Label.setObjectName("Remainder_Label")
        self.label_step2_2 = QtWidgets.QLabel(self.label_1)
        self.label_step2_2.setGeometry(QtCore.QRect(10, 260, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2_2.setFont(font)
        self.label_step2_2.setStyleSheet("color: #FFF;")
        self.label_step2_2.setObjectName("label_step2_2")
        self.label_step2 = QtWidgets.QLabel(self.label_1)
        self.label_step2.setGeometry(QtCore.QRect(10, 170, 481, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2.setFont(font)
        self.label_step2.setStyleSheet("color: #FFF;")
        self.label_step2.setObjectName("label_step2")
        self.PB_20P = QtWidgets.QPushButton(self.label_1)
        self.PB_20P.setGeometry(QtCore.QRect(300, 120, 90, 28))
        self.PB_20P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_20P.setFont(font)
        self.PB_20P.setStyleSheet("QPushButton{\n"
                                  "color:rgb(170, 255, 165);\n"
                                  "background-color: rgb(62, 62, 62);\n"
                                  "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")


        self.PB_20P.setObjectName("PB_20P")

        ############
        self.PB_20P.clicked.connect(self.pushbutton20function)

        self.PB_10P = QtWidgets.QPushButton(self.label_1)
        self.PB_10P.setGeometry(QtCore.QRect(400, 120, 90, 28))
        self.PB_10P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_10P.setFont(font)
        self.PB_10P.setStyleSheet("QPushButton{\n"
                                  "color:rgb(170, 255, 165);\n"
                                  "background-color: rgb(62, 62, 62);\n"
                                  "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.PB_10P.setObjectName("PB_10P")

        #############
        self.PB_10P.clicked.connect(self.pushbutton10function)

        self.PB_50P = QtWidgets.QPushButton(self.label_1)
        self.PB_50P.setGeometry(QtCore.QRect(200, 120, 90, 28))
        self.PB_50P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_50P.setFont(font)
        self.PB_50P.setStyleSheet("QPushButton{\n"
                                  "color:rgb(170, 255, 165);\n"
                                  "background-color: rgb(62, 62, 62);\n"
                                  "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.PB_50P.setObjectName("PB_50P")

        ###########
        self.PB_50P.clicked.connect(self.pushbutton50function)

        self.Calculate_pushButton = QtWidgets.QPushButton(self.label_1)
        self.Calculate_pushButton.setGeometry(QtCore.QRect(380, 220, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Calculate_pushButton.setFont(font)
        self.Calculate_pushButton.setStyleSheet("QPushButton{\n"
                                                "color:rgb(170, 255, 165);\n"
                                                "background-color: rgb(62, 62, 62);\n"
                                                "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Calculate_pushButton.setObjectName("Calculate_pushButton")

        ###########
        self.Calculate_pushButton.clicked.connect(self.calculatefunction)

        self.label_Step1 = QtWidgets.QLabel(self.label_1)
        self.label_Step1.setGeometry(QtCore.QRect(12, 12, 137, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1.setFont(font)
        self.label_Step1.setStyleSheet("color: #FFF;")
        self.label_Step1.setObjectName("label_Step1")
        self.PB_200P = QtWidgets.QPushButton(self.label_1)
        self.PB_200P.setGeometry(QtCore.QRect(10, 120, 90, 28))
        self.PB_200P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_200P.setFont(font)
        self.PB_200P.setStyleSheet("QPushButton{\n"
                                   "color:rgb(170, 255, 165);\n"
                                   "background-color: rgb(62, 62, 62);\n"
                                   "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.PB_200P.setObjectName("PB_200P")

        ########
        self.PB_200P.clicked.connect(self.pushbutton200function)

        self.PB_100P = QtWidgets.QPushButton(self.label_1)
        self.PB_100P.setGeometry(QtCore.QRect(110, 120, 90, 28))
        self.PB_100P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_100P.setFont(font)
        self.PB_100P.setStyleSheet("QPushButton{\n"
                                   "color:rgb(170, 255, 165);\n"
                                   "background-color: rgb(62, 62, 62);\n"
                                   "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.PB_100P.setObjectName("PB_100P")

        ########
        self.PB_100P.clicked.connect(self.pushbutton100function)

        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setGeometry(QtCore.QRect(15, 560, 460, 28))
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
                                                 "color:rgb(170, 255, 165);\n"
                                                 "background-color: rgb(62, 62, 62);\n"
                                                 "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")


######
        self.Main_Menu_Push_Button.clicked.connect(self.openWindow120)


        self.Remainder_Label2 = QtWidgets.QLabel(self.label_1)
        self.Remainder_Label2.setGeometry(QtCore.QRect(170, 340, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Remainder_Label2.setFont(font)
        self.Remainder_Label2.setStyleSheet("color:rgb(170, 255, 165);")
        self.Remainder_Label2.setText("")
        self.Remainder_Label2.setObjectName("Remainder_Label2")
        self.Display_Result_Label2 = QtWidgets.QLabel(self.label_1)
        self.Display_Result_Label2.setGeometry(QtCore.QRect(240, 300, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Display_Result_Label2.setFont(font)
        self.Display_Result_Label2.setStyleSheet("color:rgb(170, 255, 165);")
        self.Display_Result_Label2.setText("")
        self.Display_Result_Label2.setObjectName("Display_Result_Label2")
        self.Error_Label = QtWidgets.QLabel(self.label_1)
        self.Error_Label.setGeometry(QtCore.QRect(10, 400, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Error_Label.setFont(font)
        self.Error_Label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Error_Label.setText("")
        self.Error_Label.setObjectName("Error_Label")
        self.Hidden_Label = QtWidgets.QLabel(self.label_1)
        self.Hidden_Label.setGeometry(QtCore.QRect(390, 50, 55, 41))
        self.Hidden_Label.setObjectName("Hidden_Label")
        self.Hidden_Label.setHidden(True)
        Window1.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window1)
        QtCore.QMetaObject.connectSlotsByName(Window1)

    def pushbutton200function(self):
        self.Hidden_Label.setText(str(200))

    def pushbutton100function(self):
        self.Hidden_Label.setText(str(100))

    def pushbutton50function(self):
        self.Hidden_Label.setText(str(50))

    def pushbutton20function(self):
        self.Hidden_Label.setText(str(20))

    def pushbutton10function(self):
        self.Hidden_Label.setText(str(10))

    def calculatefunction(self):

        hiddenlabel = self.Hidden_Label.text()
        hiddenlabel = str(hiddenlabel)

        if hiddenlabel == "200":
            twohundredp = int(self.Ammount_input.text())
            if twohundredp < int(minimum_input):
                self.Error_Label.setText("Invalid input: smaller than minimum input")
            elif twohundredp > int(maximum_input):
                self.Error_Label.setText("Invalid input: greater than maximum input")
            else:
                two_hundred = int(twohundredp // 200)
                two_hundred_2 = int(two_hundred * 200)
                two_hundred_remainder = str(twohundredp - two_hundred_2)
                self.Display_Result_Label1.setText("Number of 200 ")
                self.Display_Result_Label2.setText(str(two_hundred))
                self.Remainder_Label2.setText(two_hundred_remainder)

        elif hiddenlabel == "100":
            onehundredp = int(self.Ammount_input.text())
            if onehundredp < int(minimum_input):
                self.Error_Label.setText("Invalid input: smaller than minimum input")
            elif onehundredp > int(maximum_input):
                self.Error_Label.setText("Invalid input: greater than maximum input")
            else:
                one_hundred = int(onehundredp // 100)
                one_hundred_2 = int(one_hundred * 100)
                one_hundred_remainder = str(onehundredp - one_hundred_2)
                self.Display_Result_Label1.setText("Number of 100 ")
                self.Display_Result_Label2.setText(str(one_hundred))
                self.Remainder_Label2.setText(one_hundred_remainder)

        elif hiddenlabel == "50":
            fiftyp = int(self.Ammount_input.text())
            if fiftyp < int(minimum_input):
                self.Error_Label.setText("Invalid input: smaller than minimum input")
            elif fiftyp > int(maximum_input):
                self.Error_Label.setText("Invalid input: greater than maximum input")
            else:
                fifty = int(fiftyp // 50)
                fifty_2 = int(fifty * 50)
                fifty_remainder = str(fiftyp - fifty_2)
                self.Display_Result_Label1.setText("Number of 50 ")
                self.Display_Result_Label2.setText(str(fifty))
                self.Remainder_Label2.setText(fifty_remainder)

        elif hiddenlabel == "20":
            twentyp = int(self.Ammount_input.text())
            if twentyp < int(minimum_input):
                self.Error_Label.setText("Invalid input: smaller than minimum input")
            elif twentyp > int(maximum_input):
                self.Error_Label.setText("Invalid input: greater than maximum input")
            else:
                twenty = int(twentyp // 20)
                twenty_2 = int(twenty * 20)
                twenty_remainder = str(twentyp - twenty_2)
                self.Display_Result_Label1.setText("Number of 20 ")
                self.Display_Result_Label2.setText(str(twenty))
                self.Remainder_Label2.setText(twenty_remainder)
        elif hiddenlabel == "10":
            tenp = int(self.Ammount_input.text())
            if tenp < int(minimum_input):
                self.Error_Label.setText("Invalid input: smaller than minimum input")
            elif tenp > int(maximum_input):
                self.Error_Label.setText("Invalid input: greater than maximum input")
            else:
                ten = int(tenp // 10)
                ten_2 = int(ten * 10)
                ten_remainder = str(tenp - ten_2)
                self.Display_Result_Label1.setText("Number of 10 ")
                self.Display_Result_Label2.setText(str(ten))
                self.Remainder_Label2.setText(ten_remainder)

        else:
            self.Error_Label.setText("please input a valid number")

    def retranslateUi(self, Window1):
        _translate = QtCore.QCoreApplication.translate
        Window1.setWindowTitle(_translate("Window1", "MainWindow"))
        self.Display_Result_Label1.setText(_translate("Window1", "Number of 200 p coins"))
        self.label_Step1_2.setText(_translate("Window1", "Step 1: Choose denomination"))

        self.Remainder_Label.setText(_translate("Window1", "Remainder:"))
        self.label_step2_2.setText(_translate("Window1", "Result:"))
        self.label_step2.setText(_translate("Window1", "Step 2: Input amount required between 0 and 10000"))
        self.PB_20P.setText(_translate("Window1", "20"))
        self.PB_10P.setText(_translate("Window1", "10 "))
        self.PB_50P.setText(_translate("Window1", "50"))
        self.Calculate_pushButton.setText(_translate("Window1", "Calculate"))
        self.label_Step1.setText(_translate("Window1", "Coin Calculator"))
        self.PB_200P.setText(_translate("Window1", "200"))
        self.PB_100P.setText(_translate("Window1", "100"))
        self.Main_Menu_Push_Button.setText(_translate("Window1", "Main Menu"))
        self.Hidden_Label.setText(_translate("Window1", "Hidden_Label"))


###########
# Page2
#########


###################
# Page2 update test
##################


class Ui_Window2(object):

    def openWindow220(self):
        self.window1_pg2 = QtWidgets.QMainWindow()
        self.ui1_pg2 = Ui_MainWindow()
        self.ui1_pg2.setupUi(self.window1_pg2)
        #Window2.hide()
        self.window1_pg2.show()


    def setupUi(self, Window2):
        Window2.setObjectName("Window2")
        Window2.resize(500, 600)
        Window2.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window2)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Step1 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1.setFont(font)
        self.label_Step1.setStyleSheet("color: #FFF;")
        self.label_Step1.setObjectName("label_Step1")
        self.gridLayout.addWidget(self.label_Step1, 0, 0, 1, 1)
        self.label_Step1_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1_2.setFont(font)
        self.label_Step1_2.setStyleSheet("color: #FFF;")
        self.label_Step1_2.setObjectName("label_Step1_2")
        self.gridLayout.addWidget(self.label_Step1_2, 1, 0, 1, 2)
        self.Ammount_input = QtWidgets.QLineEdit(self.label_1)
        self.Ammount_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ammount_input.setObjectName("Ammount_input")
        self.gridLayout.addWidget(self.Ammount_input, 2, 0, 1, 1)
        self.Calculate_PushButton = QtWidgets.QPushButton(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Calculate_PushButton.setFont(font)
        self.Calculate_PushButton.setStyleSheet("QPushButton{\n"
                                                "color:rgb(170, 255, 165);\n"
                                                "background-color: rgb(62, 62, 62);\n"
                                                "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Calculate_PushButton.setObjectName("Calculate_PushButton")

        ###########
        self.Calculate_PushButton.clicked.connect(self.calculatefuntion)

        self.gridLayout.addWidget(self.Calculate_PushButton, 2, 1, 1, 1)
        self.label_step2_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2_2.setFont(font)
        self.label_step2_2.setStyleSheet("color: #FFF;")
        self.label_step2_2.setObjectName("label_step2_2")
        self.gridLayout.addWidget(self.label_step2_2, 3, 0, 1, 1)
        self.label_step2_3 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_3.setFont(font)
        self.label_step2_3.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_3.setObjectName("label_step2_3")
        self.gridLayout.addWidget(self.label_step2_3, 4, 0, 1, 1)
        self.Output_200 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_200.setFont(font)
        self.Output_200.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_200.setObjectName("Output_200")
        self.gridLayout.addWidget(self.Output_200, 4, 1, 1, 1)
        self.label_step2_5 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_5.setFont(font)
        self.label_step2_5.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_5.setObjectName("label_step2_5")
        self.gridLayout.addWidget(self.label_step2_5, 5, 0, 1, 1)
        self.Output_100 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_100.setFont(font)
        self.Output_100.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_100.setObjectName("Output_100")
        self.gridLayout.addWidget(self.Output_100, 5, 1, 1, 1)
        self.label_step2_6 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_6.setFont(font)
        self.label_step2_6.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_6.setObjectName("label_step2_6")
        self.gridLayout.addWidget(self.label_step2_6, 6, 0, 1, 1)
        self.Output_50 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_50.setFont(font)
        self.Output_50.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_50.setObjectName("Output_50")
        self.gridLayout.addWidget(self.Output_50, 6, 1, 1, 1)
        self.label_step2_7 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_7.setFont(font)
        self.label_step2_7.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_7.setObjectName("label_step2_7")
        self.gridLayout.addWidget(self.label_step2_7, 7, 0, 1, 1)
        self.Output_20 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_20.setFont(font)
        self.Output_20.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_20.setObjectName("Output_20")
        self.gridLayout.addWidget(self.Output_20, 7, 1, 1, 1)
        self.label_step2_8 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_8.setFont(font)
        self.label_step2_8.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_8.setObjectName("label_step2_8")
        self.gridLayout.addWidget(self.label_step2_8, 8, 0, 1, 1)
        self.Output_10 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_10.setFont(font)
        self.Output_10.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_10.setObjectName("Output_10")
        self.gridLayout.addWidget(self.Output_10, 8, 1, 1, 1)
        self.label_step2_9 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_9.setFont(font)
        self.label_step2_9.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_9.setObjectName("label_step2_9")
        self.gridLayout.addWidget(self.label_step2_9, 9, 0, 1, 1)
        self.Output_remainder = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_remainder.setFont(font)
        self.Output_remainder.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_remainder.setObjectName("Output_remainder")
        self.gridLayout.addWidget(self.Output_remainder, 9, 1, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
                                                 "color:rgb(170, 255, 165);\n"
                                                 "background-color: rgb(62, 62, 62);\n"
                                                 "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")

        ##########
        #self.Main_Menu_Push_Button.clicked.connect(self.openWindow220)

        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 10, 0, 1, 1)
        Window2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window2)
        QtCore.QMetaObject.connectSlotsByName(Window2)

    def calculatefuntion(self):
        pennies = self.Ammount_input.text()
        pennies = int(pennies)
        two_hundred = pennies // 200
        two_hundred2 = two_hundred * 200
        one_hundred = (pennies % 200) // 100
        one_hundred2 = one_hundred * 100
        fifty = (pennies % 200 % 100) // 50
        fifty2 = fifty * 50
        twenty = (pennies % 200 % 100 % 50) // 20
        twenty2 = twenty * 20
        ten = (pennies % 200 % 100 % 50 % 20) // 10
        ten2 = ten * 10
        remainder = (pennies - two_hundred2 - one_hundred2 - fifty2 - twenty2 - ten2)
        self.Output_200.setText(str(two_hundred))
        self.Output_100.setText(str(one_hundred))
        self.Output_50.setText(str(fifty))
        self.Output_20.setText(str(twenty))
        self.Output_10.setText(str(ten))
        self.Output_remainder.setText(str(remainder))

    def retranslateUi(self, Window2):
        _translate = QtCore.QCoreApplication.translate
        Window2.setWindowTitle(_translate("Window2", "MainWindow"))
        self.label_Step1.setText(_translate("Window2", "Multiple Coin Calculator"))
        self.label_Step1_2.setText(_translate("Window2", "Step 1: Input how much money to be sorted"))
        self.Calculate_PushButton.setText(_translate("Window2", "Calculate"))
        self.label_step2_2.setText(_translate("Window2", "Result"))
        self.label_step2_3.setText(_translate("Window2", "The number of 200 p coins:"))
        self.Output_200.setText(_translate("Window2", "Output of 200 p"))
        self.label_step2_5.setText(_translate("Window2", "The number of 100 p coins:"))
        self.Output_100.setText(_translate("Window2", "Output of 100 p"))
        self.label_step2_6.setText(_translate("Window2", "The number of 50 p coins:"))
        self.Output_50.setText(_translate("Window2", "Output of 50 p"))
        self.label_step2_7.setText(_translate("Window2", "The number of 20 p coins:"))
        self.Output_20.setText(_translate("Window2", "Output of 20 p"))
        self.label_step2_8.setText(_translate("Window2", "The number of 10 p coins:"))
        self.Output_10.setText(_translate("Window2", "Output of 10 p"))
        self.label_step2_9.setText(_translate("Window2", "Remainder:"))
        self.Output_remainder.setText(_translate("Window2", "Output of 1-9 p"))
        self.Main_Menu_Push_Button.setText(_translate("Window2", "Main Menu"))


##########
# Page 3
##########


class Ui_Window3(object):

    def openWindow320(self):
        self.window3_pg1 = QtWidgets.QMainWindow()
        self.ui3_pg1 = Ui_MainWindow()
        self.ui3_pg1.setupUi(self.window3_pg1)
        # Window3.hide()
        self.window3_pg1.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)

        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.Window3 = QtWidgets.QLabel(self.label_1)
        self.Window3.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Window3.setFont(font)
        self.Window3.setStyleSheet("color: #FFF;")
        self.Window3.setObjectName("Window3")
        self.gridLayout.addWidget(self.Window3, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(62, 62, 62); color:rgb(170, 255, 165);")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
                                                 "color:rgb(170, 255, 165);\n"
                                                 "background-color: rgb(62, 62, 62);\n"
                                                 "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")

        self.Main_Menu_Push_Button.clicked.connect(self.openWindow320)

        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 2, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Window3.setText(_translate("MainWindow", "Coin List"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The available denominators are 10, 20, 50, 100 and 200</span></p></body></html>"))
        self.Main_Menu_Push_Button.setText(_translate("MainWindow", "Main Menu"))


###########
# Page_4
###########


class Ui_Sub_MainWindow(object):

    def openWindow_421(self):
        self.window4_1 = QtWidgets.QMainWindow()
        self.ui4_1 = Ui_Sub_Page1()
        self.ui4_1.setupUi(self.window4_1)
        # MainWindow.hide()
        self.window4_1.show()

    def openWindow_422(self):
        self.window4_2 = QtWidgets.QMainWindow()
        self.ui4_2 = Ui_Sub_Page2()
        self.ui4_2.setupUi(self.window4_2)
        # MainWindow.hide()
        self.window4_2.show()

    def openWindow_423(self):
        self.window4_3 = QtWidgets.QMainWindow()
        self.ui4_3 = Ui_Max_input_Window()
        self.ui4_3.setupUi(self.window4_3)
        # MainWindow.hide()
        self.window4_3.show()

    def openWindow_424(self):
        self.window4_4 = QtWidgets.QMainWindow()
        self.ui4_4 = Ui_MainWindow()
        self.ui4_4.setupUi(self.window4_4)
        # MainWindow.hide()
        self.window4_4.show()

    def setupUi(self, Sub_MainWindow):
        Sub_MainWindow.setObjectName("Sub_MainWindow")
        Sub_MainWindow.resize(500, 600)
        self.centralwidget = QtWidgets.QWidget(Sub_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Sub_Menu_Page = QtWidgets.QFrame(self.centralwidget)
        self.Sub_Menu_Page.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.Sub_Menu_Page.setMinimumSize(QtCore.QSize(0, 0))
        self.Sub_Menu_Page.setAutoFillBackground(False)
        self.Sub_Menu_Page.setStyleSheet("background-color:rgb(62, 62, 62);")
        self.Sub_Menu_Page.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Sub_Menu_Page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sub_Menu_Page.setObjectName("Sub_Menu_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Sub_Menu_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Menu_Header = QtWidgets.QLabel(self.Sub_Menu_Page)

        self.Main_Menu_Header.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Menu_Header.setFont(font)
        self.Main_Menu_Header.setStyleSheet("color:rgb(170, 255, 165);")
        self.Main_Menu_Header.setObjectName("Main_Menu_Header")
        self.verticalLayout.addWidget(self.Main_Menu_Header)
        self.btn_page_1 = QtWidgets.QPushButton(self.Sub_Menu_Page)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_page_1.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_1.setAutoDefault(False)
        self.btn_page_1.setDefault(False)
        self.btn_page_1.setFlat(False)
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout.addWidget(self.btn_page_1)

        self.btn_page_1.clicked.connect(self.openWindow_421)

        self.btn_page_2 = QtWidgets.QPushButton(self.Sub_Menu_Page)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout.addWidget(self.btn_page_2)

        self.btn_page_2.clicked.connect(self.openWindow_422)

        self.btn_page_3 = QtWidgets.QPushButton(self.Sub_Menu_Page)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout.addWidget(self.btn_page_3)

        self.btn_page_3.clicked.connect(self.openWindow_423)

        self.btn_page_4 = QtWidgets.QPushButton(self.Sub_Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_4.sizePolicy().hasHeightForWidth())
        self.btn_page_4.setSizePolicy(sizePolicy)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))

        self.btn_page_4.clicked.connect(self.openWindow_424)

        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_4.setFont(font)
        self.btn_page_4.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_page_4.setObjectName("btn_page_4")
        self.verticalLayout.addWidget(self.btn_page_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        Sub_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sub_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Sub_MainWindow)

    def retranslateUi(self, Sub_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Sub_MainWindow.setWindowTitle(_translate("Sub_MainWindow", "MainWindow"))
        self.Main_Menu_Header.setText(_translate("Sub_MainWindow", "Settings Menu"))
        self.btn_page_1.setText(_translate("Sub_MainWindow", "Set currency"))
        self.btn_page_2.setText(_translate("Sub_MainWindow", "Set minimum coin input value"))
        self.btn_page_3.setText(_translate("Sub_MainWindow", "Set maximum coin input value"))
        self.btn_page_4.setText(_translate("Sub_MainWindow", "Return to main menu"))


############
# Page 5
############


class Ui_Window5(object):

    def openWindow520(self):
        self.window5_pg1 = QtWidgets.QMainWindow()
        self.ui5_pg1 = Ui_MainWindow()
        self.ui5_pg1.setupUi(self.window5_pg1)
        # Window3.hide()
        self.window5_pg1.show()


    def setupUi(self, Window5):
        Window5.setObjectName("Window5")
        Window5.resize(500, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Window5.sizePolicy().hasHeightForWidth())
        Window5.setSizePolicy(sizePolicy)
        Window5.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window5)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.Header_Page5 = QtWidgets.QLabel(self.label_1)
        self.Header_Page5.setGeometry(QtCore.QRect(12, 12, 195, 60))
        self.Header_Page5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Header_Page5.setFont(font)
        self.Header_Page5.setStyleSheet("color: #FFF;")
        self.Header_Page5.setObjectName("Header_Page5")
        self.textBrowser = QtWidgets.QTextBrowser(self.label_1)
        self.textBrowser.setGeometry(QtCore.QRect(20, 170, 256, 131))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(62, 62, 62); color:rgb(170, 255, 165);")
        self.textBrowser.setObjectName("textBrowser")
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setGeometry(QtCore.QRect(15, 560, 460, 28))
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")

        ############
        self.Main_Menu_Push_Button.clicked.connect(self.openWindow520)



        self.label = QtWidgets.QLabel(self.label_1)
        self.label.setGeometry(QtCore.QRect(10, 90, 281, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(170, 255, 165);")
        self.label.setObjectName("label")
        self.Current_currency = QtWidgets.QLabel(self.label_1)
        self.Current_currency.setGeometry(QtCore.QRect(330, 100, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Current_currency.setFont(font)
        self.Current_currency.setStyleSheet("color:rgb(170, 255, 165);")
        self.Current_currency.setText("")
        self.Current_currency.setObjectName("Current_currency")
        self.label_2 = QtWidgets.QLabel(self.label_1)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 301, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.label_1)
        self.label_3.setGeometry(QtCore.QRect(20, 400, 301, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_3.setObjectName("label_3")
        self.Minimum_Input_Label = QtWidgets.QLabel(self.label_1)
        self.Minimum_Input_Label.setGeometry(QtCore.QRect(330, 340, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Minimum_Input_Label.setFont(font)
        self.Minimum_Input_Label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Minimum_Input_Label.setText("")
        self.Minimum_Input_Label.setObjectName("Minimum_Input_Label")
        self.Maximum_Input_Label = QtWidgets.QLabel(self.label_1)
        self.Maximum_Input_Label.setGeometry(QtCore.QRect(320, 400, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Maximum_Input_Label.setFont(font)
        self.Maximum_Input_Label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Maximum_Input_Label.setText("")
        self.Maximum_Input_Label.setObjectName("Maximum_Input_Label")
        Window5.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window5)
        QtCore.QMetaObject.connectSlotsByName(Window5)

        self.Current_currency.setText(str(currency_1))
        self.Minimum_Input_Label.setText(str(minimum_input))
        self.Maximum_Input_Label.setText(str(maximum_input))



    def retranslateUi(self, Window5):
        _translate = QtCore.QCoreApplication.translate
        Window5.setWindowTitle(_translate("Window5", "Display configration"))
        self.Header_Page5.setText(_translate("Window5", "Program Configration"))
        self.textBrowser.setHtml(_translate("Window5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">p = pennies (GDP) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">cent(s) = cents (USD) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">malagasey airey (MGA) </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Main_Menu_Push_Button.setText(_translate("Window5", "Main Menu"))
        self.label.setText(_translate("Window5", "The current currency setting is:"))
        self.label_2.setText(_translate("Window5", "The minimum coin input value is: "))
        self.label_3.setText(_translate("Window5", "The maximum coin input value is: "))





##################
# Submenu from page4
##################

############
# Set_Currency page
###############


class Ui_Sub_Page1(object):

    def gobackfunction(self):
        self.window5_1 = QtWidgets.QMainWindow()
        self.ui5_1 = Ui_Sub_MainWindow()
        self.ui5_1.setupUi(self.window5_1)
        # MainWindow.hide()
        self.window5_1.show()

    def setupUi(self, Sub_Page1):
        Sub_Page1.setObjectName("Sub_Page1")
        Sub_Page1.resize(500, 600)
        # Sub_Page1.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.centralwidget = QtWidgets.QWidget(Sub_Page1)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.frame.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Sub_Menu_Push_Button = QtWidgets.QPushButton(self.frame)
        self.Sub_Menu_Push_Button.setGeometry(QtCore.QRect(15, 560, 460, 28))
        self.Sub_Menu_Push_Button.setStyleSheet("QPushButton{\n"
                                                "color:rgb(170, 255, 165);\n"
                                                "background-color: rgb(62, 62, 62);\n"
                                                "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Sub_Menu_Push_Button.setObjectName("Sub_Menu_Push_Button")

        ##############
        self.Sub_Menu_Push_Button.clicked.connect(self.gobackfunction)

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 332, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(170, 255, 165);")
        self.label.setObjectName("label")
        self.GBP_PushButton = QtWidgets.QPushButton(self.frame)
        self.GBP_PushButton.setGeometry(QtCore.QRect(10, 120, 137, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.GBP_PushButton.setFont(font)
        self.GBP_PushButton.setStyleSheet("QPushButton{\n"
                                          "color:rgb(170, 255, 165);\n"
                                          "background-color: rgb(62, 62, 62);\n"
                                          "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.GBP_PushButton.setObjectName("GBP_PushButton")

        ##############
        self.GBP_PushButton.clicked.connect(self.setGBPfuntion)

        self.USD_PushButton = QtWidgets.QPushButton(self.frame)
        self.USD_PushButton.setGeometry(QtCore.QRect(10, 180, 137, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.USD_PushButton.setFont(font)
        self.USD_PushButton.setStyleSheet("QPushButton{\n"
                                          "color:rgb(170, 255, 165);\n"
                                          "background-color: rgb(62, 62, 62);\n"
                                          "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.USD_PushButton.setObjectName("USD_PushButton")

        ##########
        self.USD_PushButton.clicked.connect(self.setUSDfuntion)
        ##########

        self.Chosen_Currency_label = QtWidgets.QLabel(self.frame)
        self.Chosen_Currency_label.setGeometry(QtCore.QRect(10, 250, 464, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Chosen_Currency_label.setFont(font)
        self.Chosen_Currency_label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Chosen_Currency_label.setText("")
        self.Chosen_Currency_label.setObjectName("Chosen_Currency_label")
        Sub_Page1.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sub_Page1)
        QtCore.QMetaObject.connectSlotsByName(Sub_Page1)

    def setGBPfuntion(self):
        global currency_1
        self.Chosen_Currency_label.setText("You have selected GBP as your chosen currency")
        currency_1 = "p"

    def setUSDfuntion(self):
        global currency_1
        self.Chosen_Currency_label.setText("You have selected USD as your chosen currency")
        currency_1 = "cent(s)"

    def retranslateUi(self, Sub_Page1):
        _translate = QtCore.QCoreApplication.translate
        Sub_Page1.setWindowTitle(_translate("Sub_Page1", "Set preferred currency"))
        self.Sub_Menu_Push_Button.setText(_translate("Sub_Page1", "Back to Settings"))
        self.label.setText(_translate("Sub_Page1", "Choose preferred currency"))
        self.GBP_PushButton.setText(_translate("Sub_Page1", "GBP £"))
        self.USD_PushButton.setText(_translate("Sub_Page1", "USD $"))


############
# Set_Minimum Page
############


class Ui_Sub_Page2(object):

    def gobackfunction(self):
        self.window6_1 = QtWidgets.QMainWindow()
        self.ui6_1 = Ui_Sub_MainWindow()
        self.ui6_1.setupUi(self.window6_1)
        # MainWindow.hide()
        self.window6_1.show()

    def setupUi(self, Sub_Page2):
        Sub_Page2.setObjectName("Sub_Page2")
        Sub_Page2.resize(500, 600)
        # Sub_Page2.setGeometry(QtCore.QRect(0, 0, 500, 600))
        Sub_Page2.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.centralwidget = QtWidgets.QWidget(Sub_Page2)
        self.centralwidget.setObjectName("centralwidget")
        self.Sub_Menu_Push_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Sub_Menu_Push_Button.setGeometry(QtCore.QRect(10, 510, 454, 28))
        self.Sub_Menu_Push_Button.setStyleSheet("QPushButton{\n"
                                                "color:rgb(170, 255, 165);\n"
                                                "background-color: rgb(62, 62, 62);\n"
                                                "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Sub_Menu_Push_Button.setObjectName("Sub_Menu_Push_Button")

        ###########
        self.Sub_Menu_Push_Button.clicked.connect(self.gobackfunction)

        self.Display_min_label = QtWidgets.QLabel(self.centralwidget)
        self.Display_min_label.setGeometry(QtCore.QRect(20, 230, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Display_min_label.setFont(font)
        self.Display_min_label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Display_min_label.setText("")
        self.Display_min_label.setObjectName("Display_min_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 332, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(170, 255, 165);")
        self.label.setObjectName("label")
        self.Set_Min_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Set_Min_PushButton.setGeometry(QtCore.QRect(20, 120, 137, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Set_Min_PushButton.setFont(font)
        self.Set_Min_PushButton.setStyleSheet("QPushButton{\n"
                                              "color:rgb(170, 255, 165);\n"
                                              "background-color: rgb(62, 62, 62);\n"
                                              "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Set_Min_PushButton.setObjectName("Set_Min_PushButton")

        self.Set_Min_PushButton.clicked.connect(self.setMinfunction)

        self.Minimum_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Minimum_input.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.Minimum_input.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.Minimum_input.setObjectName("Minimum_input")
        Sub_Page2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Sub_Page2)
        QtCore.QMetaObject.connectSlotsByName(Sub_Page2)

    def setMinfunction(self):
        global minimum_input

        minimuminput = str(self.Minimum_input.text())
        minimum_input = minimuminput
        output = 'You have chosen the minimum input :', minimuminput
        # output = str("You have chosen "), str(minimuminput) , str(" as your minimum input value")
        self.Display_min_label.setText(str(output))

    def retranslateUi(self, Sub_Page2):
        _translate = QtCore.QCoreApplication.translate
        Sub_Page2.setWindowTitle(_translate("Sub_Page2", "Set miimum input"))
        self.Sub_Menu_Push_Button.setText(_translate("Sub_Page2", "Back to Settings"))
        self.label.setText(_translate("Sub_Page2", "Set minimum coin input value"))
        self.Set_Min_PushButton.setText(_translate("Sub_Page2", "Set"))


################
# Set Max input Page
################


class Ui_Max_input_Window(object):

    def gobackfunction(self):
        self.window7_1 = QtWidgets.QMainWindow()
        self.ui7_1 = Ui_Sub_MainWindow()
        self.ui7_1.setupUi(self.window7_1)
        #self.Max_input_Window.hide()
        self.window7_1.show()

    def setupUi(self, Max_input_Window):
        Max_input_Window.setObjectName("Max_input_Window")
        Max_input_Window.resize(500, 600)
        # Max_input_Window.setGeometry(QtCore.QRect(0, 0, 500, 600))
        Max_input_Window.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.centralwidget = QtWidgets.QWidget(Max_input_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.Max_input_Window_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Max_input_Window_2.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.Max_input_Window_2.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.Max_input_Window_2.setObjectName("Max_input_Window_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 332, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(170, 255, 165);")
        self.label.setObjectName("label")
        self.Sub_Menu_Push_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Sub_Menu_Push_Button.setGeometry(QtCore.QRect(10, 520, 454, 28))
        self.Sub_Menu_Push_Button.setStyleSheet("QPushButton{\n"
                                                "color:rgb(170, 255, 165);\n"
                                                "background-color: rgb(62, 62, 62);\n"
                                                "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Sub_Menu_Push_Button.setObjectName("Sub_Menu_Push_Button")

        ##########
        self.Sub_Menu_Push_Button.clicked.connect(self.gobackfunction)

        self.Display_max_label = QtWidgets.QLabel(self.centralwidget)
        self.Display_max_label.setGeometry(QtCore.QRect(10, 240, 461, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Display_max_label.setFont(font)
        self.Display_max_label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Display_max_label.setText("")
        self.Display_max_label.setObjectName("Display_max_label")
        self.Set_Max_PushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Set_Max_PushButton.setGeometry(QtCore.QRect(10, 130, 137, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Set_Max_PushButton.setFont(font)
        self.Set_Max_PushButton.setStyleSheet("QPushButton{\n"
                                              "color:rgb(170, 255, 165);\n"
                                              "background-color: rgb(62, 62, 62);\n"
                                              "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(45, 45, 45);\n"
                                      "}")
        self.Set_Max_PushButton.setObjectName("Set_Max_PushButton")

        ##########
        self.Set_Max_PushButton.clicked.connect(self.setMaxfunction)

        Max_input_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Max_input_Window)
        self.statusbar.setObjectName("statusbar")
        Max_input_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Max_input_Window)
        QtCore.QMetaObject.connectSlotsByName(Max_input_Window)

    def setMaxfunction(self):
        global maximum_input

        maximuminput = str(self.Max_input_Window_2.text())
        maximum_input = maximuminput
        output = 'You have chosen the minimum input :', maximuminput
        # output = str("You have chosen "), str(minimuminput) , str(" as your minimum input value")
        self.Display_max_label.setText(str(output))

    def retranslateUi(self, Max_input_Window):
        _translate = QtCore.QCoreApplication.translate
        Max_input_Window.setWindowTitle(_translate("Max_input_Window", "Set Maximum input"))
        self.label.setText(_translate("Max_input_Window", "Set maximum coin input value"))
        self.Sub_Menu_Push_Button.setText(_translate("Max_input_Window", "Back to Settings"))
        self.Set_Max_PushButton.setText(_translate("Max_input_Window", "Set"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    app.exec_()