# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from Page1 import Ui_Window1
# from Page2 import Ui_Window2
# from Page3 import Ui_Window3
# from Page5 import Ui_Window5

class Ui_MainWindow(object):

    def openWindow_021(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Window1()

        self.ui = Ui_Window1()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def openWindow_022(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui2 = Ui_Window2()
        self.ui2 = Ui_Window2()
        self.ui2.setupUi(self.window2)
        #MainWindow.hide()
        self.window2.show()

    def openWindow_023(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui3 = Ui_Window3()
        self.ui3.setupUi(self.window3)
        #MainWindow.hide()
        self.window3.show()

    def openWindow_025(self):
        self.window5 = QtWidgets.QMainWindow()
        self.ui5 = Ui_Window5()
        self.ui5.setupUi(self.window5)
        #MainWindow.hide()
        self.window5.show()

    def quit(self):
        self.Menu_Page.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedWidth(500)
        MainWindow.setFixedHeight(600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Menu_Page = QtWidgets.QFrame(self.centralwidget)
        self.Menu_Page.setGeometry(QtCore.QRect(0, 0, 531, 611))
        self.Menu_Page.setMinimumSize(QtCore.QSize(0, 0))
        self.Menu_Page.setAutoFillBackground(False)
        self.Menu_Page.setStyleSheet("background-color:rgb(62, 62, 62);")
        self.Menu_Page.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Menu_Page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Page.setObjectName("Menu_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Menu_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Menu_Header = QtWidgets.QLabel(self.Menu_Page)
        self.Main_Menu_Header.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Menu_Header.setFont(font)
        self.Main_Menu_Header.setStyleSheet("color:rgb(170, 255, 165);")
        self.Main_Menu_Header.setObjectName("Main_Menu_Header")
        self.verticalLayout.addWidget(self.Main_Menu_Header)
        self.btn_page_1 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_page_1.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_1.setAutoDefault(False)
        self.btn_page_1.setDefault(False)
        self.btn_page_1.setFlat(False)
        self.btn_page_1.setObjectName("btn_page_1")

        self.btn_page_1.clicked.connect(self.openWindow_021)

        self.verticalLayout.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")

        self.btn_page_2.clicked.connect(self.openWindow_022)

        self.verticalLayout.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")


        self.btn_page_3.clicked.connect(self.openWindow_023)

        self.verticalLayout.addWidget(self.btn_page_3)
        self.btn_page_4 = QtWidgets.QPushButton(self.Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_4.sizePolicy().hasHeightForWidth())
        self.btn_page_4.setSizePolicy(sizePolicy)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_4.setFont(font)
        self.btn_page_4.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")


        #self.btn_page_4.clicked.connect(self.openWindow())


        self.verticalLayout.addWidget(self.btn_page_4)
        self.btn_page_5 = QtWidgets.QPushButton(self.Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_5.sizePolicy().hasHeightForWidth())
        self.btn_page_5.setSizePolicy(sizePolicy)
        self.btn_page_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_5.setFont(font)
        self.btn_page_5.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_5.setObjectName("btn_page_5")

######
        self.btn_page_5.clicked.connect(self.openWindow_025)
#####
        self.verticalLayout.addWidget(self.btn_page_5)
        self.btn_page_6 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_6.setFont(font)
        self.btn_page_6.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_6.setObjectName("btn_page_6")

####
        self.btn_page_6.clicked.connect(self.quit)
#####
        self.verticalLayout.addWidget(self.btn_page_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Menu_Header.setText(_translate("MainWindow", "Coin Sorter - Main Menu"))
        self.btn_page_1.setText(_translate("MainWindow", "1 - Coin calculator"))
        self.btn_page_2.setText(_translate("MainWindow", "2 - Multiple coin calculator"))
        self.btn_page_3.setText(_translate("MainWindow", "3 - Print coin list"))
        self.btn_page_4.setText(_translate("MainWindow", "4 - Set details"))
        self.btn_page_5.setText(_translate("MainWindow", "5 - Display configurations details"))
        self.btn_page_6.setText(_translate("MainWindow", "6- Quit"))

############
#Page 1
############


class Ui_Window1(object):


    # def openWindow120(self):
    #     self.window1_pg1 = QtWidgets.QMainWindow()
    #     self.ui1_pg1 = Ui_MainWindow()
    #     self.ui1_pg1.setupUi(self.window1_pg1)
    #     Window1.hide()
    #     self.window1_pg1.show()

    def setupUi(self, Window1):
        Window1.setObjectName("Window1")
        MainWindow.setFixedWidth(500)
        MainWindow.setFixedHeight(600)
        Window1.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window1)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(9, 9, 481, 541))
        self.label_1.setMinimumSize(QtCore.QSize(70, 150))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.Ammount_input = QtWidgets.QLineEdit(self.label_1)
        self.Ammount_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ammount_input.setObjectName("Ammount_input")
        self.gridLayout.addWidget(self.Ammount_input, 11, 0, 1, 1)
        self.label_step2_3 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_3.setFont(font)
        self.label_step2_3.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_3.setObjectName("label_step2_3")
        self.gridLayout.addWidget(self.label_step2_3, 13, 0, 1, 1)
        self.label_Step1_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1_2.setFont(font)
        self.label_Step1_2.setStyleSheet("color: #FFF;")
        self.label_Step1_2.setObjectName("label_Step1_2")
        self.gridLayout.addWidget(self.label_Step1_2, 1, 0, 1, 1)
        self.label_step2_4 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_4.setFont(font)
        self.label_step2_4.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_4.setObjectName("label_step2_4")
        self.gridLayout.addWidget(self.label_step2_4, 14, 0, 1, 1)
        self.label_step2_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2_2.setFont(font)
        self.label_step2_2.setStyleSheet("color: #FFF;")
        self.label_step2_2.setObjectName("label_step2_2")
        self.gridLayout.addWidget(self.label_step2_2, 12, 0, 1, 1)
        self.label_step2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2.setFont(font)
        self.label_step2.setStyleSheet("color: #FFF;")
        self.label_step2.setObjectName("label_step2")
        self.gridLayout.addWidget(self.label_step2, 10, 0, 1, 2)
        self.PB_20P = QtWidgets.QPushButton(self.label_1)
        self.PB_20P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_20P.setFont(font)
        self.PB_20P.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_20P.setObjectName("PB_20P")
        self.gridLayout.addWidget(self.PB_20P, 7, 0, 1, 1)
        self.PB_10P = QtWidgets.QPushButton(self.label_1)
        self.PB_10P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_10P.setFont(font)
        self.PB_10P.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_10P.setObjectName("PB_10P")
        self.gridLayout.addWidget(self.PB_10P, 8, 0, 1, 1)
        self.PB_50P = QtWidgets.QPushButton(self.label_1)
        self.PB_50P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_50P.setFont(font)
        self.PB_50P.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_50P.setObjectName("PB_50P")
        self.gridLayout.addWidget(self.PB_50P, 6, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 11, 1, 1, 1)
        self.label_Step1 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1.setFont(font)
        self.label_Step1.setStyleSheet("color: #FFF;")
        self.label_Step1.setObjectName("label_Step1")
        self.gridLayout.addWidget(self.label_Step1, 0, 0, 1, 2)
        self.PB_2Pounds = QtWidgets.QPushButton(self.label_1)
        self.PB_2Pounds.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_2Pounds.setFont(font)
        self.PB_2Pounds.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_2Pounds.setObjectName("PB_2Pounds")
        self.gridLayout.addWidget(self.PB_2Pounds, 3, 0, 1, 1)
        self.PB_1Pound = QtWidgets.QPushButton(self.label_1)
        self.PB_1Pound.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_1Pound.setFont(font)
        self.PB_1Pound.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_1Pound.setObjectName("PB_1Pound")
        self.gridLayout.addWidget(self.PB_1Pound, 4, 0, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")
##############
#        self.Main_Menu_Push_Button.clicked.connect(self.openWindow120)
##############
        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 15, 0, 1, 1)
        Window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        Window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window1)
        self.statusbar.setObjectName("statusbar")
        Window1.setStatusBar(self.statusbar)

        self.retranslateUi(Window1)
        QtCore.QMetaObject.connectSlotsByName(Window1)

    def retranslateUi(self, Window1):
        _translate = QtCore.QCoreApplication.translate
        Window1.setWindowTitle(_translate("Window1", "MainWindow"))
        self.label_step2_3.setText(_translate("Window1", "denminated number"))
        self.label_Step1_2.setText(_translate("Window1", "Step 1: Choose denomination"))
        self.label_step2_4.setText(_translate("Window1", "Remainder:"))
        self.label_step2_2.setText(_translate("Window1", "Result"))
        self.label_step2.setText(_translate("Window1", "Step 2: Input amount required"))
        self.PB_20P.setText(_translate("Window1", "20 P"))
        self.PB_10P.setText(_translate("Window1", "10 P"))
        self.PB_50P.setText(_translate("Window1", "50 P"))
        self.pushButton.setText(_translate("Window1", "Submit"))
        self.label_Step1.setText(_translate("Window1", "Coin Calculator"))
        self.PB_2Pounds.setText(_translate("Window1", "£2"))
        self.PB_1Pound.setText(_translate("Window1", "£1"))
        self.Main_Menu_Push_Button.setText(_translate("Window1", "Main Menu"))

###########
#Page2
#########


# class Ui_Window2(object):
#     # def openWinndow220(self):
#     #     self.window = QtWidgets.QMainWindow()
#     #     self.ui = Ui_MainWindow()
#     #     self.ui.setupUi(self.window)
#     #     Window2.hide()
#     #     self.window.show()
#
#     def setupUi(self, Window2):
#         Window2.setObjectName("Window2")
#         Window2.resize(500, 600)
#         Window2.setMinimumSize(QtCore.QSize(500, 600))
#         self.centralwidget = QtWidgets.QWidget(Window2)
#         self.centralwidget.setObjectName("centralwidget")
#         self.label_1 = QtWidgets.QFrame(self.centralwidget)
#         self.label_1.setGeometry(QtCore.QRect(10, 10, 481, 541))
#         self.label_1.setMinimumSize(QtCore.QSize(0, 0))
#         self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
#         self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
#         self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.label_1.setObjectName("label_1")
#         self.label_Step1 = QtWidgets.QLabel(self.label_1)
#         self.label_Step1.setGeometry(QtCore.QRect(12, 12, 214, 22))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         font.setBold(True)
#         font.setUnderline(True)
#         font.setWeight(75)
#         self.label_Step1.setFont(font)
#         self.label_Step1.setStyleSheet("color: #FFF;")
#         self.label_Step1.setObjectName("label_Step1")
#         self.label_Step1_2 = QtWidgets.QLabel(self.label_1)
#         self.label_Step1_2.setGeometry(QtCore.QRect(12, 69, 397, 22))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         font.setBold(True)
#         font.setUnderline(True)
#         font.setWeight(75)
#         self.label_Step1_2.setFont(font)
#         self.label_Step1_2.setStyleSheet("color: #FFF;")
#         self.label_Step1_2.setObjectName("label_Step1_2")
#         self.Ammount_input = QtWidgets.QLineEdit(self.label_1)
#         self.Ammount_input.setGeometry(QtCore.QRect(12, 128, 137, 24))
#         self.Ammount_input.setStyleSheet("background-color: rgb(255, 255, 255);")
#         self.Ammount_input.setObjectName("Ammount_input")
#         self.Calculate_PushButton = QtWidgets.QPushButton(self.label_1)
#         self.Calculate_PushButton.setGeometry(QtCore.QRect(332, 126, 93, 28))
#         font = QtGui.QFont()
#         font.setPointSize(9)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Calculate_PushButton.setFont(font)
#         self.Calculate_PushButton.setStyleSheet("QPushButton{\n"
# "color:rgb(170, 255, 165);\n"
# "background-color: rgb(62, 62, 62);\n"
# "}")
#         self.Calculate_PushButton.setObjectName("Claculate_PushButton")
#
#         ##########
#         self.Calculate_PushButton.clicked.connect(self.calculatefuntion)
# ############
#
#         self.label_step2_2 = QtWidgets.QLabel(self.label_1)
#         self.label_step2_2.setGeometry(QtCore.QRect(12, 161, 57, 22))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         font.setBold(True)
#         font.setUnderline(True)
#         font.setWeight(75)
#         self.label_step2_2.setFont(font)
#         self.label_step2_2.setStyleSheet("color: #FFF;")
#         self.label_step2_2.setObjectName("label_step2_2")
#         self.label_step2_3 = QtWidgets.QLabel(self.label_1)
#         self.label_step2_3.setGeometry(QtCore.QRect(12, 217, 235, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_step2_3.setFont(font)
#         self.label_step2_3.setStyleSheet("color:rgb(170, 255, 165);")
#         self.label_step2_3.setObjectName("label_step2_3")
#         self.Output_200 = QtWidgets.QLabel(self.label_1)
#         self.Output_200.setGeometry(QtCore.QRect(332, 217, 137, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Output_200.setFont(font)
#         self.Output_200.setStyleSheet("color:rgb(170, 255, 165);")
#         self.Output_200.setObjectName("Output_200")
#         self.label_step2_5 = QtWidgets.QLabel(self.label_1)
#         self.label_step2_5.setGeometry(QtCore.QRect(12, 274, 235, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_step2_5.setFont(font)
#         self.label_step2_5.setStyleSheet("color:rgb(170, 255, 165);")
#         self.label_step2_5.setObjectName("label_step2_5")
#         self.Output_100 = QtWidgets.QLabel(self.label_1)
#         self.Output_100.setGeometry(QtCore.QRect(332, 274, 137, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Output_100.setFont(font)
#         self.Output_100.setStyleSheet("color:rgb(170, 255, 165);")
#         self.Output_100.setObjectName("Output_100")
#         self.label_step2_6 = QtWidgets.QLabel(self.label_1)
#         self.label_step2_6.setGeometry(QtCore.QRect(12, 331, 224, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_step2_6.setFont(font)
#         self.label_step2_6.setStyleSheet("color:rgb(170, 255, 165);")
#         self.label_step2_6.setObjectName("label_step2_6")
#         self.Output_50 = QtWidgets.QLabel(self.label_1)
#         self.Output_50.setGeometry(QtCore.QRect(332, 331, 126, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Output_50.setFont(font)
#         self.Output_50.setStyleSheet("color:rgb(170, 255, 165);")
#         self.Output_50.setObjectName("Output_50")
#         self.label_step2_7 = QtWidgets.QLabel(self.label_1)
#         self.label_step2_7.setGeometry(QtCore.QRect(12, 388, 224, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_step2_7.setFont(font)
#         self.label_step2_7.setStyleSheet("color:rgb(170, 255, 165);")
#         self.label_step2_7.setObjectName("label_step2_7")
#         self.Output_20 = QtWidgets.QLabel(self.label_1)
#         self.Output_20.setGeometry(QtCore.QRect(332, 388, 126, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Output_20.setFont(font)
#         self.Output_20.setStyleSheet("color:rgb(170, 255, 165);")
#         self.Output_20.setObjectName("Output_20")
#         self.label_step2_8 = QtWidgets.QLabel(self.label_1)
#         self.label_step2_8.setGeometry(QtCore.QRect(12, 444, 224, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_step2_8.setFont(font)
#         self.label_step2_8.setStyleSheet("color:rgb(170, 255, 165);")
#         self.label_step2_8.setObjectName("label_step2_8")
#
#         self.Output_10 = QtWidgets.QLabel(self.label_1)
#         self.Output_10.setGeometry(QtCore.QRect(332, 444, 126, 21))
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Output_10.setFont(font)
#         self.Output_10.setStyleSheet("color:rgb(170, 255, 165);")
#         self.Output_10.setObjectName("Output_10")
#         self.label_step2_9 = QtWidgets.QLabel(self.label_1)
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_step2_9.setFont(font)
#         self.label_step2_9.setStyleSheet("color:rgb(170, 255, 165);")
#         self.label_step2_9.setObjectName("label_step2_9")
#         self.gridLayout.addWidget(self.label_step2_9, 9, 0, 1, 1)
#         self.Output_remainder = QtWidgets.QLabel(self.label_1)
#         font = QtGui.QFont()
#         font.setPointSize(10)
#         font.setBold(True)
#         font.setWeight(75)
#         self.Output_remainder.setFont(font)
#         self.Output_remainder.setStyleSheet("color:rgb(170, 255, 165);")
#         self.Output_remainder.setObjectName("Output_remainder")
#         self.gridLayout.addWidget(self.Output_remainder, 9, 1, 1, 1)
#
#         self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
#         self.Main_Menu_Push_Button.setGeometry(QtCore.QRect(12, 501, 93, 28))
#         self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
# "color:rgb(170, 255, 165);\n"
# "background-color: rgb(62, 62, 62);\n"
# "}")
#         self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")
# ###########
# #        self.Main_Menu_Push_Button.clicked.connect(self.openWinndow220)
# ##########
#         Window2.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(Window2)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
#         self.menubar.setObjectName("menubar")
#         Window2.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(Window2)
#         self.statusbar.setObjectName("statusbar")
#         Window2.setStatusBar(self.statusbar)
#
#         self.retranslateUi(Window2)
#         QtCore.QMetaObject.connectSlotsByName(Window2)
#
#     def calculatefuntion(self):
#         pennies = self.Ammount_input.text()
#         pennies = int(pennies)
#         two_hundred = pennies // 200
#         two_hundred2 = two_hundred * 200
#         one_hundred = (pennies % 200) // 100
#         one_hundred2 = one_hundred * 100
#         fifty = (pennies % 200 % 100) // 50
#         fifty2 = fifty * 50
#         twenty = (pennies % 200 % 100 % 50) // 20
#         twenty2 = twenty * 20
#         ten = (pennies % 200 % 100 % 50 % 20) // 10
#         ten2 = ten * 10
#         remainder = (pennies - two_hundred2 - one_hundred2 - fifty2 - twenty2 - ten2)
#         self.Output_200.setText(str(two_hundred))
#         self.Output_100.setText(str(one_hundred))
#         self.Output_50.setText(str(fifty))
#         self.Output_20.setText(str(twenty))
#         self.Output_10.setText(str(ten))
#         self.Output_remainder.setText((remainder))
#
#
#
#
#
#
#     def retranslateUi(self, Window2):
#         _translate = QtCore.QCoreApplication.translate
#         Window2.setWindowTitle(_translate("Window2", "MainWindow"))
#         self.label_Step1.setText(_translate("Window2", "Multiple Coin Calculator"))
#         self.label_Step1_2.setText(_translate("Window2", "Step 1: Input how much money to be sorted"))
#         self.Calculate_PushButton.setText(_translate("Window2", "Submit"))
#         self.label_step2_2.setText(_translate("Window2", "Result"))
#         self.label_step2_3.setText(_translate("Window2", "The number of 200 p coins:"))
#         self.Output_200.setText(_translate("Window2", "Output of 200 p"))
#         self.label_step2_5.setText(_translate("Window2", "The number of 100 p coins:"))
#         self.Output_100.setText(_translate("Window2", "Output of 100 p"))
#         self.label_step2_6.setText(_translate("Window2", "The number of 50 p coins:"))
#         self.Output_50.setText(_translate("Window2", "Output of 50 p"))
#         self.label_step2_7.setText(_translate("Window2", "The number of 20 p coins:"))
#         self.Output_20.setText(_translate("Window2", "Output of 20 p"))
#         self.label_step2_8.setText(_translate("Window2", "The number of 10 p coins:"))
#         self.Output_10.setText(_translate("Window2", "Output of 10 p"))
#         self.label_step2_9.setText(_translate("Window2", "Remainder:"))
#         self.Output_remainder.setText(_translate("Window2", "Output of 1-9 p"))
#         self.Main_Menu_Push_Button.setText(_translate("Window2", "Main Menu"))
#


###################
#Page2 update test
##################



class Ui_Window2(object):
    def setupUi(self, Window2):
        Window2.setObjectName("Window2")
        Window2.resize(500, 600)
        Window2.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window2)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Step1 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1.setFont(font)
        self.label_Step1.setStyleSheet("color: #FFF;")
        self.label_Step1.setObjectName("label_Step1")
        self.gridLayout.addWidget(self.label_Step1, 0, 0, 1, 1)
        self.label_Step1_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1_2.setFont(font)
        self.label_Step1_2.setStyleSheet("color: #FFF;")
        self.label_Step1_2.setObjectName("label_Step1_2")
        self.gridLayout.addWidget(self.label_Step1_2, 1, 0, 1, 2)
        self.Ammount_input = QtWidgets.QLineEdit(self.label_1)
        self.Ammount_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ammount_input.setObjectName("Ammount_input")
        self.gridLayout.addWidget(self.Ammount_input, 2, 0, 1, 1)
        self.Calculate_PushButton = QtWidgets.QPushButton(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Calculate_PushButton.setFont(font)
        self.Calculate_PushButton.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Calculate_PushButton.setObjectName("Calculate_PushButton")

 ###########
        self.Calculate_PushButton.clicked.connect(self.calculatefuntion)

        self.gridLayout.addWidget(self.Calculate_PushButton, 2, 1, 1, 1)
        self.label_step2_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2_2.setFont(font)
        self.label_step2_2.setStyleSheet("color: #FFF;")
        self.label_step2_2.setObjectName("label_step2_2")
        self.gridLayout.addWidget(self.label_step2_2, 3, 0, 1, 1)
        self.label_step2_3 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_3.setFont(font)
        self.label_step2_3.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_3.setObjectName("label_step2_3")
        self.gridLayout.addWidget(self.label_step2_3, 4, 0, 1, 1)
        self.Output_200 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_200.setFont(font)
        self.Output_200.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_200.setObjectName("Output_200")
        self.gridLayout.addWidget(self.Output_200, 4, 1, 1, 1)
        self.label_step2_5 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_5.setFont(font)
        self.label_step2_5.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_5.setObjectName("label_step2_5")
        self.gridLayout.addWidget(self.label_step2_5, 5, 0, 1, 1)
        self.Output_100 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_100.setFont(font)
        self.Output_100.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_100.setObjectName("Output_100")
        self.gridLayout.addWidget(self.Output_100, 5, 1, 1, 1)
        self.label_step2_6 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_6.setFont(font)
        self.label_step2_6.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_6.setObjectName("label_step2_6")
        self.gridLayout.addWidget(self.label_step2_6, 6, 0, 1, 1)
        self.Output_50 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_50.setFont(font)
        self.Output_50.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_50.setObjectName("Output_50")
        self.gridLayout.addWidget(self.Output_50, 6, 1, 1, 1)
        self.label_step2_7 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_7.setFont(font)
        self.label_step2_7.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_7.setObjectName("label_step2_7")
        self.gridLayout.addWidget(self.label_step2_7, 7, 0, 1, 1)
        self.Output_20 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_20.setFont(font)
        self.Output_20.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_20.setObjectName("Output_20")
        self.gridLayout.addWidget(self.Output_20, 7, 1, 1, 1)
        self.label_step2_8 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_8.setFont(font)
        self.label_step2_8.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_8.setObjectName("label_step2_8")
        self.gridLayout.addWidget(self.label_step2_8, 8, 0, 1, 1)
        self.Output_10 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_10.setFont(font)
        self.Output_10.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_10.setObjectName("Output_10")
        self.gridLayout.addWidget(self.Output_10, 8, 1, 1, 1)
        self.label_step2_9 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_9.setFont(font)
        self.label_step2_9.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_9.setObjectName("label_step2_9")
        self.gridLayout.addWidget(self.label_step2_9, 9, 0, 1, 1)
        self.Output_remainder = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Output_remainder.setFont(font)
        self.Output_remainder.setStyleSheet("color:rgb(170, 255, 165);")
        self.Output_remainder.setObjectName("Output_remainder")
        self.gridLayout.addWidget(self.Output_remainder, 9, 1, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")
        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 10, 0, 1, 1)
        Window2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window2)
        QtCore.QMetaObject.connectSlotsByName(Window2)

    def calculatefuntion(self):
        pennies = self.Ammount_input.text()
        pennies = int(pennies)
        two_hundred = pennies // 200
        two_hundred2 = two_hundred * 200
        one_hundred = (pennies % 200) // 100
        one_hundred2 = one_hundred * 100
        fifty = (pennies % 200 % 100) // 50
        fifty2 = fifty * 50
        twenty = (pennies % 200 % 100 % 50) // 20
        twenty2 = twenty * 20
        ten = (pennies % 200 % 100 % 50 % 20) // 10
        ten2 = ten * 10
        remainder = (pennies - two_hundred2 - one_hundred2 - fifty2 - twenty2 - ten2)
        self.Output_200.setText(str(two_hundred))
        self.Output_100.setText(str(one_hundred))
        self.Output_50.setText(str(fifty))
        self.Output_20.setText(str(twenty))
        self.Output_10.setText(str(ten))
        self.Output_remainder.setText(str(remainder))

    def retranslateUi(self, Window2):
        _translate = QtCore.QCoreApplication.translate
        Window2.setWindowTitle(_translate("Window2", "MainWindow"))
        self.label_Step1.setText(_translate("Window2", "Multiple Coin Calculator"))
        self.label_Step1_2.setText(_translate("Window2", "Step 1: Input how much money to be sorted"))
        self.Calculate_PushButton.setText(_translate("Window2", "Calculate"))
        self.label_step2_2.setText(_translate("Window2", "Result"))
        self.label_step2_3.setText(_translate("Window2", "The number of 200 p coins:"))
        self.Output_200.setText(_translate("Window2", "Output of 200 p"))
        self.label_step2_5.setText(_translate("Window2", "The number of 100 p coins:"))
        self.Output_100.setText(_translate("Window2", "Output of 100 p"))
        self.label_step2_6.setText(_translate("Window2", "The number of 50 p coins:"))
        self.Output_50.setText(_translate("Window2", "Output of 50 p"))
        self.label_step2_7.setText(_translate("Window2", "The number of 20 p coins:"))
        self.Output_20.setText(_translate("Window2", "Output of 20 p"))
        self.label_step2_8.setText(_translate("Window2", "The number of 10 p coins:"))
        self.Output_10.setText(_translate("Window2", "Output of 10 p"))
        self.label_step2_9.setText(_translate("Window2", "Remainder:"))
        self.Output_remainder.setText(_translate("Window2", "Output of 1-9 p"))
        self.Main_Menu_Push_Button.setText(_translate("Window2", "Main Menu"))


##########
#Page 3
##########


class Ui_Window3(object):

    # def openWindow320(self):
    #     self.window3_pg1 = QtWidgets.QMainWindow()
    #     self.ui3_pg1 = Ui_MainWindow()
    #     self.ui3_pg1.setupUi(self.window3_pg1)
    #     Window3.hide()
    #     self.window3_pg1.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 607)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.Window3 = QtWidgets.QLabel(self.label_1)
        self.Window3.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Window3.setFont(font)
        self.Window3.setStyleSheet("color: #FFF;")
        self.Window3.setObjectName("Window3")
        self.gridLayout.addWidget(self.Window3, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(62, 62, 62); color:rgb(170, 255, 165);")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")

#        self.Main_Menu_Push_Button.clicked.connect(self.openWinndow320)



        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 2, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Window3.setText(_translate("MainWindow", "Coin List"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The available denominators are 10, 20, 50, 100 and 200</span></p></body></html>"))
        self.Main_Menu_Push_Button.setText(_translate("MainWindow", "Main Menu"))


############
#Page 5
############


class Ui_Window5(object):
    def setupUi(self, Window5):
        Window5.setObjectName("Window5")
        Window5.resize(509, 600)
        Window5.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window5)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 0, 510, 534))
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.Header_Page5 = QtWidgets.QLabel(self.label_1)
        self.Header_Page5.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Header_Page5.setFont(font)
        self.Header_Page5.setStyleSheet("color: #FFF;")
        self.Header_Page5.setObjectName("Header_Page5")
        self.gridLayout.addWidget(self.Header_Page5, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(62, 62, 62); color:rgb(170, 255, 165);")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")
        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 2, 0, 1, 1)
        Window5.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 26))
        self.menubar.setObjectName("menubar")
        Window5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window5)
        self.statusbar.setObjectName("statusbar")
        Window5.setStatusBar(self.statusbar)

        self.retranslateUi(Window5)
        QtCore.QMetaObject.connectSlotsByName(Window5)

    def retranslateUi(self, Window5):
        _translate = QtCore.QCoreApplication.translate
        Window5.setWindowTitle(_translate("Window5", "MainWindow"))
        self.Header_Page5.setText(_translate("Window5", "Program Configration"))
        self.textBrowser.setHtml(_translate("Window5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The current currency setting is: p</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">p = pennies (GDP) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">cent(s) = cents (USD) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">malagasey airey (MGA) </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The minimum coin input value is:  0</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The maximum coin input value is:  10000</p></body></html>"))
        self.Main_Menu_Push_Button.setText(_translate("Window5", "Main Menu"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

