# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_Designer_Menu2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStackedWidget


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 526)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Menu_Bar = QtWidgets.QFrame(self.frame)
        self.Menu_Bar.setGeometry(QtCore.QRect(0, -10, 278, 541))
        self.Menu_Bar.setAutoFillBackground(False)
        self.Menu_Bar.setStyleSheet("background-color:rgb(62, 62, 62);")
        self.Menu_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Menu_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Bar.setObjectName("Menu_Bar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Menu_Bar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Menu_Label = QtWidgets.QLabel(self.Menu_Bar)
        self.Main_Menu_Label.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Menu_Label.setFont(font)
        self.Main_Menu_Label.setStyleSheet("color:rgb(170, 255, 165);")
        self.Main_Menu_Label.setObjectName("Main_Menu_Label")
        self.verticalLayout.addWidget(self.Main_Menu_Label)
        self.btn_menu_1 = QtWidgets.QPushButton(self.Menu_Bar)
        self.btn_menu_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_1.setFont(font)
        self.btn_menu_1.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_menu_1.setObjectName("btn_menu_1")
        self.verticalLayout.addWidget(self.btn_menu_1)
        self.pushButton = QtWidgets.QPushButton(self.Menu_Bar)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.Menu_Bar)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "color:rgb(170, 255, 165);\n"
                                        "background-color: rgb(62, 62, 62);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color:rgb(51, 32, 74);\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.btn_menu_2 = QtWidgets.QPushButton(self.Menu_Bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_2.sizePolicy().hasHeightForWidth())
        self.btn_menu_2.setSizePolicy(sizePolicy)
        self.btn_menu_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_2.setFont(font)
        self.btn_menu_2.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_menu_2.setObjectName("btn_menu_2")
        self.verticalLayout.addWidget(self.btn_menu_2)
        self.btn_menu_3 = QtWidgets.QPushButton(self.Menu_Bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu_3.sizePolicy().hasHeightForWidth())
        self.btn_menu_3.setSizePolicy(sizePolicy)
        self.btn_menu_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_3.setFont(font)
        self.btn_menu_3.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_menu_3.setObjectName("btn_menu_3")
        self.verticalLayout.addWidget(self.btn_menu_3)
        self.btn_menu_4 = QtWidgets.QPushButton(self.Menu_Bar)
        self.btn_menu_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_menu_4.setFont(font)
        self.btn_menu_4.setStyleSheet("QPushButton{\n"
                                      "color:rgb(170, 255, 165);\n"
                                      "background-color: rgb(62, 62, 62);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(51, 32, 74);\n"
                                      "}")
        self.btn_menu_4.setObjectName("btn_menu_4")
        self.verticalLayout.addWidget(self.btn_menu_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Content = QtWidgets.QFrame(self.frame)
        self.Content.setGeometry(QtCore.QRect(270, 0, 741, 551))
        self.Content.setAutoFillBackground(False)
        self.Content.setStyleSheet("\n"
                                   "background-color:rgb(51, 32, 74);")
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Content)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 49, 681, 181))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_menu_4.clicked.connect(self.clicked_menu_button)

    def clicked_menu_button(self):
        self.stackedWidget.addWidget(self.page_4)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Menu_Label.setText(_translate("MainWindow", "Coin Sorter - Main Menu"))
        self.btn_menu_1.setText(_translate("MainWindow", "1 - Coin calculator"))
        self.pushButton.setText(_translate("MainWindow", "2 - Multiple coin calculator"))
        self.pushButton_2.setText(_translate("MainWindow", "3 - Print coin list"))
        self.btn_menu_2.setText(_translate("MainWindow", "4 - Set details"))
        self.btn_menu_3.setText(_translate("MainWindow", "5 - Display configurations details"))
        self.btn_menu_4.setText(_translate("MainWindow", "6- Quit"))

        # self.btn_menu_4.triggered.connect(Page_4)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
