# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Page1 import Ui_Window1
from Page2 import Ui_Window2
from Page3 import Ui_Window3
from Page5 import Ui_Window5

class Ui_MainWindow(object):

    def openWindow_021(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Window1()

        self.ui = Ui_Window3()
        # self.ui = Ui_Window5()
        self.ui.setupUi(self.window)
        #MainWindow.hide()
        self.window.show()

    def openWindow_022(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui2 = Ui_Window2()
        self.ui2.setupUi(self.window2)
        #MainWindow.hide()
        self.window2.show()

    def openWindow_023(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui3 = Ui_Window3()
        self.ui3.setupUi(self.window3)
        #MainWindow.hide()
        self.window3.show()

    def openWindow_025(self):
        self.window5 = QtWidgets.QMainWindow()
        self.ui5 = Ui_Window5()
        self.ui5.setupUi(self.window5)
        #MainWindow.hide()
        self.window5.show()

    def quit(self):
        self.Menu_Page.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 671)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Menu_Page = QtWidgets.QFrame(self.centralwidget)
        self.Menu_Page.setGeometry(QtCore.QRect(0, 0, 531, 611))
        self.Menu_Page.setMinimumSize(QtCore.QSize(0, 0))
        self.Menu_Page.setAutoFillBackground(False)
        self.Menu_Page.setStyleSheet("background-color:rgb(62, 62, 62);")
        self.Menu_Page.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Menu_Page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu_Page.setObjectName("Menu_Page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Menu_Page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_Menu_Header = QtWidgets.QLabel(self.Menu_Page)
        self.Main_Menu_Header.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Main_Menu_Header.setFont(font)
        self.Main_Menu_Header.setStyleSheet("color:rgb(170, 255, 165);")
        self.Main_Menu_Header.setObjectName("Main_Menu_Header")
        self.verticalLayout.addWidget(self.Main_Menu_Header)
        self.btn_page_1 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_page_1.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_1.setAutoDefault(False)
        self.btn_page_1.setDefault(False)
        self.btn_page_1.setFlat(False)
        self.btn_page_1.setObjectName("btn_page_1")

        self.btn_page_1.clicked.connect(self.openWindow_021)

        self.verticalLayout.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")

        self.btn_page_2.clicked.connect(self.openWindow_022)

        self.verticalLayout.addWidget(self.btn_page_2)
        self.btn_page_3 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_3.setObjectName("btn_page_3")


        self.btn_page_3.clicked.connect(self.openWindow_023)

        self.verticalLayout.addWidget(self.btn_page_3)
        self.btn_page_4 = QtWidgets.QPushButton(self.Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_4.sizePolicy().hasHeightForWidth())
        self.btn_page_4.setSizePolicy(sizePolicy)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_4.setFont(font)
        self.btn_page_4.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")


        #self.btn_page_4.clicked.connect(self.openWindow())


        self.verticalLayout.addWidget(self.btn_page_4)
        self.btn_page_5 = QtWidgets.QPushButton(self.Menu_Page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_page_5.sizePolicy().hasHeightForWidth())
        self.btn_page_5.setSizePolicy(sizePolicy)
        self.btn_page_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_5.setFont(font)
        self.btn_page_5.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_5.setObjectName("btn_page_5")

######
        self.btn_page_5.clicked.connect(self.openWindow_025)
#####
        self.verticalLayout.addWidget(self.btn_page_5)
        self.btn_page_6 = QtWidgets.QPushButton(self.Menu_Page)
        self.btn_page_6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page_6.setFont(font)
        self.btn_page_6.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(51, 32, 74);\n"
"}")
        self.btn_page_6.setObjectName("btn_page_6")

####
        self.btn_page_6.clicked.connect(self.quit)
#####
        self.verticalLayout.addWidget(self.btn_page_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_Menu_Header.setText(_translate("MainWindow", "Coin Sorter - Main Menu"))
        self.btn_page_1.setText(_translate("MainWindow", "1 - Coin calculator"))
        self.btn_page_2.setText(_translate("MainWindow", "2 - Multiple coin calculator"))
        self.btn_page_3.setText(_translate("MainWindow", "3 - Print coin list"))
        self.btn_page_4.setText(_translate("MainWindow", "4 - Set details"))
        self.btn_page_5.setText(_translate("MainWindow", "5 - Display configurations details"))
        self.btn_page_6.setText(_translate("MainWindow", "6- Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
