# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from Menu_Page import Ui_MainWindow

class Ui_Window1(object):

    #
    # def openWindow120(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_MainWindow()
    #     self.ui.setupUi(self.window)
    #     #Window1.hide()
    #     self.window.show()
    #
    def setupUi(self, Window1):
        Window1.setObjectName("Window1")
        Window1.resize(500, 600)
        Window1.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(Window1)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(9, 9, 481, 541))
        self.label_1.setMinimumSize(QtCore.QSize(70, 150))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.Ammount_input = QtWidgets.QLineEdit(self.label_1)
        self.Ammount_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Ammount_input.setObjectName("Ammount_input")
        self.gridLayout.addWidget(self.Ammount_input, 11, 0, 1, 1)
        self.label_step2_3 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_3.setFont(font)
        self.label_step2_3.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_3.setObjectName("label_step2_3")
        self.gridLayout.addWidget(self.label_step2_3, 13, 0, 1, 1)
        self.label_Step1_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1_2.setFont(font)
        self.label_Step1_2.setStyleSheet("color: #FFF;")
        self.label_Step1_2.setObjectName("label_Step1_2")
        self.gridLayout.addWidget(self.label_Step1_2, 1, 0, 1, 1)
        self.label_step2_4 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_step2_4.setFont(font)
        self.label_step2_4.setStyleSheet("color:rgb(170, 255, 165);")
        self.label_step2_4.setObjectName("label_step2_4")
        self.gridLayout.addWidget(self.label_step2_4, 14, 0, 1, 1)
        self.label_step2_2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2_2.setFont(font)
        self.label_step2_2.setStyleSheet("color: #FFF;")
        self.label_step2_2.setObjectName("label_step2_2")
        self.gridLayout.addWidget(self.label_step2_2, 12, 0, 1, 1)
        self.label_step2 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_step2.setFont(font)
        self.label_step2.setStyleSheet("color: #FFF;")
        self.label_step2.setObjectName("label_step2")
        self.gridLayout.addWidget(self.label_step2, 10, 0, 1, 2)
        self.PB_20P = QtWidgets.QPushButton(self.label_1)
        self.PB_20P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_20P.setFont(font)
        self.PB_20P.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_20P.setObjectName("PB_20P")
        self.gridLayout.addWidget(self.PB_20P, 7, 0, 1, 1)
        self.PB_10P = QtWidgets.QPushButton(self.label_1)
        self.PB_10P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_10P.setFont(font)
        self.PB_10P.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_10P.setObjectName("PB_10P")
        self.gridLayout.addWidget(self.PB_10P, 8, 0, 1, 1)
        self.PB_50P = QtWidgets.QPushButton(self.label_1)
        self.PB_50P.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_50P.setFont(font)
        self.PB_50P.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_50P.setObjectName("PB_50P")
        self.gridLayout.addWidget(self.PB_50P, 6, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 11, 1, 1, 1)
        self.label_Step1 = QtWidgets.QLabel(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Step1.setFont(font)
        self.label_Step1.setStyleSheet("color: #FFF;")
        self.label_Step1.setObjectName("label_Step1")
        self.gridLayout.addWidget(self.label_Step1, 0, 0, 1, 2)
        self.PB_2Pounds = QtWidgets.QPushButton(self.label_1)
        self.PB_2Pounds.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_2Pounds.setFont(font)
        self.PB_2Pounds.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_2Pounds.setObjectName("PB_2Pounds")
        self.gridLayout.addWidget(self.PB_2Pounds, 3, 0, 1, 1)
        self.PB_1Pound = QtWidgets.QPushButton(self.label_1)
        self.PB_1Pound.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PB_1Pound.setFont(font)
        self.PB_1Pound.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.PB_1Pound.setObjectName("PB_1Pound")
        self.gridLayout.addWidget(self.PB_1Pound, 4, 0, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")
##############
        #self.Main_Menu_Push_Button.clicked.connect(self.openWindow120)
##############
        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 15, 0, 1, 1)
        Window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        Window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window1)
        self.statusbar.setObjectName("statusbar")
        Window1.setStatusBar(self.statusbar)

        self.retranslateUi(Window1)
        QtCore.QMetaObject.connectSlotsByName(Window1)

    def retranslateUi(self, Window1):
        _translate = QtCore.QCoreApplication.translate
        Window1.setWindowTitle(_translate("Window1", "MainWindow"))
        self.label_step2_3.setText(_translate("Window1", "denminated number"))
        self.label_Step1_2.setText(_translate("Window1", "Step 1: Choose denomination"))
        self.label_step2_4.setText(_translate("Window1", "Remainder:"))
        self.label_step2_2.setText(_translate("Window1", "Result"))
        self.label_step2.setText(_translate("Window1", "Step 2: Input amount required"))
        self.PB_20P.setText(_translate("Window1", "20 P"))
        self.PB_10P.setText(_translate("Window1", "10 P"))
        self.PB_50P.setText(_translate("Window1", "50 P"))
        self.pushButton.setText(_translate("Window1", "Submit"))
        self.label_Step1.setText(_translate("Window1", "Coin Calculator"))
        self.PB_2Pounds.setText(_translate("Window1", "£2"))
        self.PB_1Pound.setText(_translate("Window1", "£1"))
        self.Main_Menu_Push_Button.setText(_translate("Window1", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window1 = QtWidgets.QMainWindow()
    ui = Ui_Window1()
    ui.setupUi(Window1)
    Window1.show()
    sys.exit(app.exec_())
