# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 607)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QFrame(self.centralwidget)
        self.label_1.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1.setStyleSheet("background-color:rgb(51, 32, 74);")
        self.label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_1.setObjectName("label_1")
        self.gridLayout = QtWidgets.QGridLayout(self.label_1)
        self.gridLayout.setObjectName("gridLayout")
        self.Window3 = QtWidgets.QLabel(self.label_1)
        self.Window3.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Window3.setFont(font)
        self.Window3.setStyleSheet("color: #FFF;")
        self.Window3.setObjectName("Window3")
        self.gridLayout.addWidget(self.Window3, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.label_1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(62, 62, 62); color:rgb(170, 255, 165);")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.Main_Menu_Push_Button = QtWidgets.QPushButton(self.label_1)
        self.Main_Menu_Push_Button.setStyleSheet("QPushButton{\n"
"color:rgb(170, 255, 165);\n"
"background-color: rgb(62, 62, 62);\n"
"}")
        self.Main_Menu_Push_Button.setObjectName("Main_Menu_Push_Button")
        self.gridLayout.addWidget(self.Main_Menu_Push_Button, 2, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Window3.setText(_translate("MainWindow", "Coin List"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The available denominators are 10, 20, 50, 100 and 200</span></p></body></html>"))
        self.Main_Menu_Push_Button.setText(_translate("MainWindow", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Window3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
